### ISSUE TITLE
Task list for PR #81

### ISSUE THREAD

**Issue by zethon** [zethon/Owl#82]
### Code Maintenance
- [x] Get rid of `servicesTree`
- [x] Get rid of `_svcModel` if possible
- [x] Get rid of `MainWindow::getCurrentForum()` if possible
- [ ] Replace `Board::readableHash()` to use UUID
- [x] Rename `servicesTree2` to `servicesTree`
- [ ] Get rid of the app toolbar along the top that is hidden by default

### New Features
- [x] Add UUID to each board
- [ ] Hash/UUID for threads (useable in MainWindow::newThreadHandler())
- [ ] Hash/UUID for posts
